<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerACsoxZo\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerACsoxZo/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerACsoxZo.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerACsoxZo\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerACsoxZo\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'ACsoxZo',
    'container.build_id' => 'f6e3781f',
    'container.build_time' => 1668047956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerACsoxZo');
